version: "3"

services:
  app:
    build:
      context: .
    container_name: app
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - node-network
    ports:
      - "8080:80"
    restart: always
    tty: true
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
